### ISSUE TITLE
Isn't working anymore (IDE 16.8)

### ISSUE THREAD

**Issue by d3221** [koen-github/WakeOnLan-ESP8266#2]
Hey,

I just copied your example code and when I compile it there is this error:
_unable to find numeric literal operator 'operator"" R'_

Already tried to perform a Google Search; but there is just a solution that doens't work (do every single package in " " ).

Any ideas or fixes?
Like in the title said i have the Arduino 1.6.8

I included your libary but it seems to be an Arduino problem in combination with the syntax maybe?

**Comment by koenieee** [comment]
Hello D3221, 

DId you try to use the newest Arduino IDE, I think that will be version 1.8.x? 

I will look into it when I got some spare time.

Kind regrards,

Koen

**Comment by d3221** [comment]
Hey,

I tried it with 1.8.2 & 1.8.5 too.

Thank you :)

**Comment by koenieee** [comment]
Did that work? Or did you get the same problem?

**Comment by d3221** [comment]
Still same problem; thank you for having a look for the problem I meant. :)

**Comment by bondar** [comment]
Same issue for me as well.

**Comment by bondar** [comment]
The code has:
`byte mac[6] = { 0xFR, 0xBB, 0x34, 0xE5, 0x29, 0xFC };`
change it to:
`byte mac[6] = { 0xFE, 0xBB, 0x34, 0xE5, 0x29, 0xFC };`
That will fix the compilation issue -- the issue is with 0xFR which isn't a valid hex value, changing it to 0xFE (or better - the machine's actual mac) makes it a valid hex value.

**Comment by koenieee** [comment]
Thanks, I changed it 👍
